export const actions = [
  "Who is most likely to drunk text their ex at 3 AM?",
  "Who is most likely to wake up in a different city with no memory of how they got there?",
  "Who is most likely to get kicked out of a bar?",
  "Who is most likely to hook up with someone they met 5 minutes ago?",
  "Who is most likely to start a fight over something stupid?",
  "Who is most likely to become a stripper if they needed money fast?",
  "Who is most likely to get arrested for public indecency?",
  "Who is most likely to lie about their body count?",
  "Who is most likely to steal someone's partner?",
  "Who is most likely to fake an orgasm?",
  "Who is most likely to sleep with their boss?",
  "Who is most likely to join a cult?",
  "Who is most likely to get catfished?",
  "Who is most likely to accidentally send nudes to their parents?",
  "Who is most likely to have a threesome?",
  "Who is most likely to cry during sex?",
  "Who is most likely to get caught having sex in public?",
  "Who is most likely to marry someone for money?",
  "Who is most likely to cheat on their partner?",
  "Who is most likely to have a secret OnlyFans?",
  "Who is most likely to hook up with their friend's sibling?",
  "Who is most likely to ghost someone after one date?",
  "Who is most likely to get roofied because they're too trusting?",
  "Who is most likely to start a bar fight over a sports team?",
  "Who is most likely to pee in the pool?",
  "Who is most likely to have a one-night stand and never call back?",
  "Who is most likely to accidentally set something on fire while drunk?",
  "Who is most likely to break up with someone over text?",
  "Who is most likely to get plastic surgery and deny it?",
  "Who is most likely to have a sugar daddy/mommy?",
  "Who is most likely to get banned from Tinder?",
  "Who is most likely to hook up with someone from this group?",
  "Who is most likely to throw up on someone during a night out?",
  "Who is most likely to steal food off someone else's plate?",
  "Who is most likely to have tried drugs they won't admit to?",
  "Who is most likely to be into some freaky shit in bed?",
  "Who is most likely to get a tattoo they'll regret while drunk?",
  "Who is most likely to stalk their ex on social media daily?",
  "Who is most likely to lie about their age on dating apps?",
  "Who is most likely to have the highest body count in this room?",
  "Who is most likely to get caught watching porn?",
  "Who is most likely to have a fake ID?",
  "Who is most likely to join the Mile High Club?",
  "Who is most likely to have shower sex and slip?",
  "Who is most likely to get divorced within 2 years of marriage?",
  "Who is most likely to have hooked up with a coworker?",
  "Who is most likely to have a secret Pornhub account?",
  "Who is most likely to get kicked off a plane?",
  "Who is most likely to hook up with a celebrity?",
  "Who is most likely to become a cougar/silver fox?",
  "Who is most likely to get pregnant/get someone pregnant by accident?",
  "Who is most likely to lie about being on birth control?",
  "Who is most likely to have herpes and not tell anyone?",
  "Who is most likely to be into BDSM?",
  "Who is most likely to pay for sex?",
  "Who is most likely to have had sex in their parents' bed?",
  "Who is most likely to pretend to be gay to get free drinks?",
  "Who is most likely to have road rage and run someone off the road?",
  "Who is most likely to get way too drunk and embarrass everyone?",
  "Who is most likely to hook up with their Uber driver?",
  "Who is most likely to slide into someone's DMs right now?",
  "Who is most likely to get caught sexting during a work meeting?",
  "Who is most likely to have a sex tape leaked?",
  "Who is most likely to date someone 20 years older/younger?",
  "Who is most likely to fake an accent to seem more interesting?",
  "Who is most likely to get banned from a country?",
  "Who is most likely to start an illegal business?",
  "Who is most likely to have a secret family?",
  "Who is most likely to become famous on TikTok for something stupid?",
  "Who is most likely to sell drugs to make extra cash?",
  "Who is most likely to be a swinger?",
  "Who is most likely to have a secret foot fetish?",
  "Who is most likely to steal from a friend?",
  "Who is most likely to fake their own death for insurance money?",
  "Who is most likely to become a cam girl/boy?",
  "Who is most likely to have hooked up with their therapist?",
  "Who is most likely to get fired for hooking up in the office?",
  "Who is most likely to become a homewrecker?",
  "Who is most likely to buy bath water from an influencer?",
  "Who is most likely to catfish someone?",
  "Who is most likely to have a burner phone for shady shit?",
  "Who is most likely to get caught masturbating?",
  "Who is most likely to have a weird porn addiction?",
  "Who is most likely to date multiple people at once and get caught?",
  "Who is most likely to fake a pregnancy?",
  "Who is most likely to marry someone they just met in Vegas?",
  "Who is most likely to blackmail someone?",
  "Who is most likely to have used their roommate's toothbrush?",
  "Who is most likely to eat ass on the first date?",
  "Who is most likely to get kicked out of an all-you-can-eat buffet?",
  "Who is most likely to hit on their friend's parent?",
  "Who is most likely to have fucked someone in this room?",
  "Who is most likely to lie about being in a relationship?",
  "Who is most likely to have a secret Grindr/dating app account?",
  "Who is most likely to get caught cheating by leaving their phone unlocked?",
  "Who is most likely to have a freaky role-play kink?",
  "Who is most likely to get arrested at a protest?",
  "Who is most likely to have hooked up with their best friend's ex?",
  "Who is most likely to accidentally like their crush's photo from 3 years ago?",
  "Who is most likely to have crabs right now?",
  "Who is most likely to get deported?",
  "Who is most likely to have shoplifted and never got caught?",
  "Who is most likely to become a drug dealer's accountant?",
  "Who is most likely to hire a hitman?",
  "Who is most likely to become a stripper's best customer?",
  "Who is most likely to get caught having sex by their parents?",
  "Who is most likely to hook up at a funeral?",
  "Who is most likely to get herpes from a toilet seat (if that was actually possible)?",
  "Who is most likely to fake being rich on Instagram?",
  "Who is most likely to sleep with someone for concert tickets?",
  "Who is most likely to have an embarrassing safe word?",
  "Who is most likely to get kicked out of a wedding?",
  "Who is most likely to have hooked up with their cousin by accident?",
  "Who is most likely to have a secret mommy/daddy kink?",
  "Who is most likely to ruin someone's relationship with a screenshot?",
  "Who is most likely to get caught doing cocaine in a bathroom?",
  "Who is most likely to be a terrible wingman and steal the person instead?",
  "Who is most likely to have hooked up with someone from Craigslist?",
  "Who is most likely to get plastic surgery and lie about it being 'just good genes'?",
  "Who is most likely to hook up with their professor for a better grade?",
  "Who is most likely to get caught stealing from work?",
  "Who is most likely to fake a hate crime for attention?",
  "Who is most likely to become a Karen and ask for the manager?",
  "Who is most likely to have a secret breeding kink?",
  "Who is most likely to get caught peeping on someone?",
  "Who is most likely to become an alcoholic?",
  "Who is most likely to have fucked someone in their friend group and never told anyone?",
  "Who is most likely to get banned from social media for being too wild?",
  "Who is most likely to scam old people online?",
  "Who is most likely to have a fetish they're too embarrassed to admit?",
  "Who is most likely to become a trophy wife/husband?",
];
